train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['Hardhat', 'NO-Hardhat']

roboflow:
  workspace: 1-txx8f
  project: 123123-ilpj4
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/1-txx8f/123123-ilpj4/dataset/1