train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['Hardhat', 'NO-Hardhat']

roboflow:
  workspace: 1-txx8f
  project: v5-t27ww
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/1-txx8f/v5-t27ww/dataset/1