spring:
  application:
    name: elderly-care-system
  datasource:
    # ????????localhost?????3306????elderly_care???????
    url: jdbc:mysql://localhost:3306/elderly_care?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # ??????????? root
    username: root
    # ???????????????? MySQL ???????
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.elderlycare.entity
  configuration:
    map-underscore-to-camel-case: true # ????????????user_name -> Java userName?